csv_path: "data/01_raw/Car_Prices_Poland_Kaggle.csv"
current_year: 2025
test_size: 0.2
random_state: 42
ag_label: "price"
ag_output_path: "data/06_models/autogluon/"
time_limit: 600
presets:
  - best_quality
eval_metric: "root_mean_squared_error"
